✨ [feat] 막걸리 정보 뷰 작업 work in progress
DeveloperAcademy-POSTECH/MacC-Team-1010 pull request #11
Opened 2023-10-19 16:02 UTC by jieun0330

## Motivation
- issue number : InformationView #10 

## Changes
- View 작업중입니다.
- 작업 완료되서 PR 올리는 것이 아니라서 코드가 정리되있지 않습니다.

## Screen Shots
|기능|스크린샷|
|::|:--:|
|||

## To Reviewers
- 잔소리 주세요

2023-10-20 04:10 UTC, mininim reviewed
수고하셨슴돵!
이후에 MockMakgeolliModel 형식에 대해서 같이 이야기 해보면 좋을 것 같습니다~

2023-10-20 04:10 UTC, mininim commented on Projects/FeatureInformation/Scene/TasteRatingView.swift
> +                    Text("단맛")
P5 - 이후 상세 구현할때 참고하면 좋을 것 같아요! 
TestRatingView 구현하는 것보니 MockMakgeolliModel을 수정해도 좋을 것 같습니다!

taste 종류는 단맛, 신맛, 걸쭉함, 청량감 고정되어있어서 이런식으로 MockMakgeolliModel에서 description은 View에서 고정된 값으로 로 넣어도 충분할 것 같아요.
tasteScore를 구조체로 구현해서 각 맛별로 프로퍼티 만드는 것도 좋을 것 같슴돠!

2023-10-20 07:09 UTC, ungchun commented on Projects/FeatureInformation/Scene/ContentView.swift
> +                }
p3
이렇게도 쓰는군요.. 정답은 없다지만 코드 통일성을 맞추기 위해 background color 세팅은 View 하단으로 옮겨주세요! 😀

2023-10-20 07:12 UTC, ungchun commented on Projects/FeatureInformation/Scene/ContentView.swift
> +public struct ContentView: View {
p1
이 친구가 메인 뷰 인거 같은데, ContentView -> InformationView로 네이밍 수정해주세요! 😀

2023-10-20 07:12 UTC, ungchun commented on Projects/FeatureInformation/Scene/ContentView.swift
> +struct ContentView_Previews: PreviewProvider {
빈 줄은 1줄만!

2023-10-20 07:13 UTC, ungchun commented on Projects/FeatureInformation/Scene/MarkHolyView.swift
> +            .overlay(
p3
위에 코멘트랑 똑같은 내용입니다 :)

2023-10-20 07:15 UTC, ungchun commented
작업이 얼추 마무리되면 추가로 리뷰 진행할게요!

주석은 다 삭제해주시고 공백 4~5줄 있는거 다 지워주세요!
그리고 간격이나 레이아웃이 안맞는 부분들이 많이 보이는데, command + a (전체 선택) 후 control + i 하면 코드 정리되니까 꼭 해주세요!! 😄

2023-10-20 07:56 UTC, M1zz requested changes
순조롭게 진행되고 있군요! 
코딩 다 하고 변경 요청사항 받는 것 보다 변경사항을 받아가며 코딩하는게
완성하는데 더 짧은 시간이 들어갑니다 ㅎ ㅎ

2023-10-20 07:56 UTC, M1zz commented on Projects/FeatureInformation/Scene/ContentView.swift
> +    public init() {}
p2
이친구 init은 왜 필요한가요?

2023-10-20 07:56 UTC, M1zz commented on Projects/FeatureInformation/Scene/ContentView.swift
> +    @State private var clickHeart: Bool = false
p4
isHeartClicked 는 어떠신가요? true가 어떤 상태일지 상상이 안가서요!

2023-10-20 07:56 UTC, M1zz commented on Projects/FeatureInformation/Scene/ContentView.swift
> +//                                                    .foregroundColor(.yellowHeart)
p1
안쓰는 주석은 다 지워주셔도 괜찮습니다 깃에 기록이 다 남기에 어떤 코드가 있었는지는 잘 파악할 수 있습니다 :)

2023-10-21 02:57 UTC, ungchun commented on Projects/FeatureInformation/Scene/PreviousPageView.swift
> +//        NavigationView {
p1
사용안하는 뷰, 테스트했던 뷰는 삭제해주세요..!

2023-10-21 03:04 UTC, ungchun commented on Projects/FeatureInformation/Scene/InformationView.swift
> +    }
p5
이거 제가 component로 만들어놨는데, 추후에 머지하고 이 부분 삭제하고 component로 수정해주세요 :)

2023-10-21 03:05 UTC, ungchun commented on Projects/FeatureInformation/Scene/MarkHoly/MarkHolyView.swift
> +}
p1
파일만들어서 따로 빼주세요!!

2023-10-21 03:06 UTC, ungchun commented on Projects/FeatureInformation/Scene/MarkHoly/MarkHolyView.swift
> +            HStack {
p2
이름을 마크홀리로 만든 이유가 있을까요? 🧐 
특별한 이유가 없다면, 조금 더 공통적으로 쓸 수 있는 네이밍을 고려해주세요! 😄

2023-10-21 03:10 UTC, ungchun commented on Projects/FeatureInformation/Scene/TasteRating/TasteRatingView.swift
> +}
p2
요 친구도 파일 만들어서 따로 빼주세요!

2023-10-21 03:13 UTC, ungchun commented on Projects/FeatureInformation/Scene/TasteRating/TasteRatingView.swift
> +    case taste1 = 1
p2
taste5, 4, 3, 2, 1 이라는 네이밍 말고 다른 네이밍으로 수정해주셨으면 좋겠어요!
예를 들어 맛에 관련한 점수 이런 식으로 접근해도 좋을 거 같아요. 1, 2, 3, 4, 5 이런 네이밍만 아니었으면.. 🧐

2023-10-21 03:13 UTC, ungchun commented on Projects/FeatureInformation/Scene/TasteRating/TasteRatingView.swift
> +    @State private var tasteRating4: TasteRating = .taste2
p2
위에 적은 네이밍 관련해서 동일합니다!

2023-10-21 03:16 UTC, ungchun requested changes
코멘트 확인해서 늦어도 일요일까지 적용해서 다시 올려주세요! :)

2023-10-21 10:35 UTC, jieun0330 commented on Projects/FeatureInformation/Scene/InformationView.swift
> +    }
> p5 이거 제가 component로 만들어놨는데, 추후에 머지하고 이 부분 삭제하고 component로 수정해주세요 :)

네에~!

2023-10-21 10:42 UTC, jieun0330 commented on Projects/FeatureInformation/Scene/MarkHoly/MarkHolyView.swift
> +            HStack {
> p2 MarkHolyDetail, MaryHolyView, MarkHoly 이름을 마크홀리로 만든 이유가 있을까요? 🧐 특별한 이유가 없다면, 조금 더 공통적으로 쓸 수 있는 네이밍을 고려해주세요! 😄

막걸리를 영어로 마크홀리로 하는게 좋을거같아서,, ㅎ
makgeolli 로 바꿀까요?

2023-10-21 10:44 UTC, jieun0330 commented on Projects/FeatureInformation/Scene/TasteRating/TasteRatingView.swift
> +    case taste1 = 1
> p2 taste5, 4, 3, 2, 1 이라는 네이밍 말고 다른 네이밍으로 수정해주셨으면 좋겠어요! 예를 들어 맛에 관련한 점수 이런 식으로 접근해도 좋을 거 같아요. 1, 2, 3, 4, 5 이런 네이밍만 아니었으면.. 🧐

단맛, 신맛 으로 가면 좋겠다는 말씀이실까요 ?.?

2023-10-21 11:25 UTC, ungchun commented on Projects/FeatureInformation/Scene/MarkHoly/MarkHolyView.swift
> +            HStack {
아.. ㅋㅋㅋㅋㅋ 네넵 makgeolli로 해주시고 추후에 한번에 수정합시다! 😄

2023-10-21 11:26 UTC, ungchun commented on Projects/FeatureInformation/Scene/TasteRating/TasteRatingView.swift
> +    case taste1 = 1
음 어떻게든 상관없는데, 의미가 있는 이름이었으면 좋겠습니다! 단맛, 신맛 이렇게 가도 괜찮구요 :)

2023-10-21 15:42 UTC, jieun0330 commented on Projects/FeatureInformation/Scene/TasteRating/TasteRatingView.swift
> +    case taste1 = 1
> 음 어떻게든 상관없는데, 의미가 있는 이름이었으면 좋겠습니다! 단맛, 신맛 이렇게 가도 괜찮구요 :)

근데 맛 평가 점수에 관한건데 taste 5,4,3,2,1이 아닌 어떻게 네이밍을 해야된다는건지 감이 안와요,,!
best, good, bad 이런 식으로 해야된다는건지,,

2023-10-21 15:52 UTC, ungchun commented on Projects/FeatureInformation/Scene/TasteRating/TasteRatingView.swift
> +    case taste1 = 1
음.. 저도 작업을 한게 아니라서 잘 안그려지긴 하는데, 어차피 갈아야하는 코드니까 우선 이렇게 가고 같이 이야기해봅시다! 😄

2023-10-21 16:57 UTC, mininim commented on Projects/FeatureInformation/Scene/TasteRating/TasteRatingView.swift
> +    @State private var tasteRating4: TasteRating = .taste2
p2
각 맛의 정도(점수)에 대한 정보는 one, two, three, four, five 로 해도 좋을 것 같슴돠! 
tasteRating1 , tasteRating2, tasteRating3 tasteRating4를 각 맛별로 이름 지어서 Taste 구조체를 만들어도 좋을 것 같아요!
개인적으로 열거형 익숙치 않은데 굉장히 쏘 신기~  점찍으면 자동완성 쏘 굳~

```
 @State private var tasteRating1: TasteRating = .one
 @State private var tasteRating2: TasteRating = .four
 @State private var tasteRating3: TasteRating = .three
 @State private var tasteRating4: TasteRating = .two
 
 struct Taste {
    var sweetness: TasteRating
    var sourness: TasteRating
    var thickness: TasteRating
    var freshness: TasteRating
}
```

2023-10-21 17:06 UTC, mininim commented on Projects/FeatureInformation/Scene/MarkHoly/MarkHolyView.swift
> +            HStack {
근데 MarkHoly보니까 MakGeolli  lli <- 요거 쏘 불편ㅋㅋ
MarkHoly 네이밍이 볼때랑 타자치기에 좀 좋아보이김함요

2023-10-22 07:36 UTC, ungchun approved these changes
LGTM 👍

2023-10-22 07:37 UTC, merged