#26/Data Model, Tab Bar구현
DeveloperAcademy-POSTECH/MacC-Team-1010 pull request #32
Opened 2023-10-31 12:47 UTC by jieun0330

## Motivation
- issue number : #26 

## Changes
- 썸네일 내 들어가는 정보를 Model로 빼두었습니다.
- Tab Bar 1차적으로 구현했습니다.

## Screen Shots
![simulator_screenshot_10E29815-FF0F-49A5-B326-53456FE58EE5](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-1010/assets/42729069/b99b22b3-3d99-46f3-ad98-6162d01fae99)

## To Reviewers
- Tab Bar를 슬라이드 형식으로 변경할 예정입니다.
- 좋았어요, 아쉬워요, 찜, 코멘트 클릭시 바뀌는 형식은 Data 받으면 변경할 예정입니다.
- NavigationBarTitle(?) 내 막걸리도 추가할 예정입니다.
- 수정할게 많지만 우선 올립니다!

2023-10-31 14:01 UTC, ungchun commented on Projects/DesignSystem/Sources/Colors/Color.swift
> +	case darkGrey
p1

darkgrey가 맞는 거라서 현재 develop에 darkgrey로 제가 따로 수정해서 push 해놨어요. 나중에 merge 할 때 darkgrey로 꼭 수정해서 merge 해주세요!

2023-10-31 14:03 UTC, ungchun commented on Projects/FeatureEncyclopedia/Model/ThumbnailModel.swift
> +
p1

Model 위치는 Core -> Models로 이동시켜주세요! 🧐

2023-10-31 14:06 UTC, ungchun commented on Projects/FeatureEncyclopedia/Model/ThumbnailView.swift
> +//}
p4
preview를 안쓰면 주석은 지워도 괜찮지 않을까요..? 😄

2023-10-31 14:13 UTC, ungchun commented on Projects/FeatureEncyclopedia/Scene/CommentView.swift
> +    let columns: [GridItem] = Array(repeating: .init(.fixed(110)), count: 3)
👍

2023-10-31 14:15 UTC, ungchun commented on Projects/FeatureEncyclopedia/Scene/TabPageView.swift
> +
p5
요런 공백은 두줄보다는 한줄로 맞춰주는게 보기 좋아요 😄

2023-10-31 17:20 UTC, jieun0330 commented on Projects/FeatureEncyclopedia/Model/ThumbnailModel.swift
> +
Core -> Models 안에 어디 폴더에 두면 될까요 ?.?

2023-10-31 17:24 UTC, jieun0330 commented on Projects/FeatureEncyclopedia/Model/ThumbnailView.swift
> +                            model.comment
이건 내일 대면으로 물어볼게요!

2023-11-02 03:23 UTC, mininim reviewed
탭뷰 애니메이션 쏘기대~

2023-11-02 03:23 UTC, mininim commented on Projects/FeatureEncyclopedia/Scene/Thumbnail/Thumbnail.swift
> +
p2
Model분리 쏘나이스~

1. 
Model에는 각 상태별 정보를 저장하면 좋을 것 같습니다.
막걸리의 제품이미지를 제외한 코멘트/찜/저장/좋아요나빠요 이미지는 고정되어있으니 
각 이미지는 ThumbnailView에서 넣어두고 보여줄지에 대한 정보를 담으면 좋을 것 같습니다. 

[좋았어요 / 아쉬워요 / 선택안함]
[코멘드 있음 / 코멘트 없음]
[찜O / 찜X]
이렇게 3가지 정보들의 상태에 따라서 ThumbnailView가 달라질 수 있도록요!

```
public struct Thumbnail: Identifiable {
    public let id = UUID()
    var likeState: LikeState 
    var IsSaved: Bool
    var isCommented: Bool
    var name: String
  ...
}
```

2.
product를 likedImage 등으로 변경하면 더 읽기 좋아 질 것 같아요


추가로 Core/ Models /  MakHoly 새로 추가된 데이터 모델들 있으니  한번 참고해보면 좋을 것 같습니다.
MakHoly 타입에도

2023-11-02 08:22 UTC, M1zz requested changes

2023-11-02 08:22 UTC, M1zz commented on Projects/FeatureEncyclopedia/Model/ThumbnailModel.swift
> +import Foundation
p3 이거 없어도 동작하지 않나요?

2023-11-02 08:22 UTC, M1zz commented on Projects/FeatureEncyclopedia/Scene/Tab/TabMenuView.swift
> +                    if pageId == 0 {
p1 id == 0 이 무슨 케이스죠? switch case 문으로 바꿔주세요!

2023-11-02 08:22 UTC, M1zz commented on Projects/FeatureEncyclopedia/Scene/View/GoodView.swift
> +    public var dummyModel = Thumbnail.dummyThumbNailModel
p1 이곳 저곳에서 더미모델을 쓰는데 변수로 받아와서 쓸 필요 있나요? 심지어 public 이라...

2023-11-04 11:19 UTC, ungchun approved these changes
👍

2023-11-04 11:20 UTC, merged