#70/내막걸리View API 데이터 적용
DeveloperAcademy-POSTECH/MacC-Team-1010 pull request #77
Opened 2023-11-10 17:23 UTC by jieun0330

## Motivation
- issue number : #70 

## Changes
- 내막걸리View에 API 데이터 적용 했습니다.

## Screen Shots
![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-1010/assets/42729069/d5d59aa2-ac57-4e52-948f-567ad35751bf)

## To Reviewers
- API는 모두 적용했습니다.

- 코멘트 수정 시 TextField에 기존 작성되어있던 코멘트 보이게 하기
- TextField 상단 부분 불필요한 여백 삭제
- TextField 텍스트 입력 시 키보드 보이게 하기
- 코멘트 공개/비공개 여부 적용
- 코멘트 수정/삭제/저장 시 데이터 수정/삭제/저장 적용

-> 다음주 월요일까지 작업 마치겠습니다,,

2023-11-11 00:19 UTC, mininim reviewed
오!👍  API 연결 쏘 어썸~
Text들에 컬러안들어간것들하고 , 옵셔널 확인만 부탁드려요~

2023-11-11 00:19 UTC, mininim commented on Projects/FeatureEncyclopedia/Scene/EncyclopediaViewModel.swift
> +                testModel = (response.result?.makUserTable!.content!) ?? []
p2
Response 타입으로 그대로 사용하니까 여기서 옵셔널 확인 안전하게하면 좋을 것 같아요

```
if let content = response.result?.makUserTable?.content {
    testModel = content
} else {
    testModel = []
}
```

2023-11-11 00:19 UTC, mininim commented on Projects/FeatureEncyclopedia/Scene/Thumbnail/ThumbnailView.swift
> +                        .lineLimit(1)
p1
컬러 추가해주세여~

2023-11-11 00:19 UTC, mininim commented on Projects/FeatureEncyclopedia/Scene/View/CommentView.swift
> +                                    Text(mak.makNm!)
p1 
컬러 추가요~ 
그리고 textModel mak 프로퍼티들 사용할때 아래처럼 만이라도 옵셔널 확인하고 사용하면 좋을 것 같아요!

```
mak.makNm ?? ""
```

2023-11-11 06:18 UTC, ungchun commented on Projects/FeatureEncyclopedia/Scene/EncyclopediaViewModel.swift
> +    @Published var testModel: [GetUserMakFolderContent] = []
p2
네이밍 수정해주세요!

2023-11-11 06:19 UTC, ungchun commented on Projects/FeatureEncyclopedia/Scene/EncyclopediaViewModel.swift
> +                print("resposne = \(response)")
p3
print도 삭제해주세요! 😀

2023-11-11 06:21 UTC, ungchun commented on Projects/FeatureEncyclopedia/Scene/Thumbnail/ThumbnailView.swift
> +                    MakHolyImageView(imageId: mak.makImg!, type: .middle)
```suggestion
                    MakHolyImageView(imageId: mak.makImg ?? -1, type: .middle)
```
p3
makImg가 안들어오지는 않을 거 같은데.. 혹시나 모르니까 이런 방법으로 옵셔널을 처리하는게 어떨까요?

2023-11-11 06:22 UTC, ungchun requested changes
고생하셨습니다!
에릭하고 제가 남긴 코멘트 확인하시고 재 리뷰 요청 주세요! 😄

2023-11-12 12:29 UTC, jieun0330 commented on Projects/FeatureEncyclopedia/Scene/Thumbnail/ThumbnailView.swift
> +                    MakHolyImageView(imageId: mak.makImg!, type: .middle)
-1은 뭐에요??

2023-11-12 12:55 UTC, ungchun commented on Projects/FeatureEncyclopedia/Scene/Thumbnail/ThumbnailView.swift
> +                    MakHolyImageView(imageId: mak.makImg!, type: .middle)
-1이 의미가 있다기 보다는, 그냥 예시를 들었습니다. 만약 makImg가 null로 들어오면 앱이 죽어버리기 때문에 에러 로직 처리를 하면 좋겠다. 라는 뜻이에요!

2023-11-12 16:32 UTC, ungchun commented on Projects/FeatureEncyclopedia/Scene/View/CommentView.swift
> +                                    Text(mak.makNm!)
이 부분 빠진거 같은데 확인해주세요! 🧐

2023-11-12 16:33 UTC, ungchun approved these changes
에릭 코멘트 적용안된부분 있는 거 같은데, 그것만 올려주시면 될 거 같아서 우선 approve 하곘습니다! 😄

2023-11-13 14:34 UTC, merged